"""idempotency constraints and query indexes

Revision ID: 22f35bdc2221
Revises: 66c6c53196b8
Create Date: 2026-07-25 15:49:00.459172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22f35bdc2221'
down_revision: Union[str, None] = '66c6c53196b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_clients_user_platform_client', ['user_id', 'platform_client_id'])

    with op.batch_alter_table('exchange_connections', schema=None) as batch_op:
        batch_op.create_index('uq_connections_user_exchange', ['user_id', 'platform'], unique=True, sqlite_where=sa.text("platform != 'tg_channel'"), postgresql_where=sa.text("platform != 'tg_channel'"))

    with op.batch_alter_table('project_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_analyses_user_computed', ['user_id', 'computed_at'], unique=False)
        batch_op.create_unique_constraint('uq_analysis_project_user', ['project_id', 'user_id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_status_due', ['status', 'due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_status_due')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_created_at')

    with op.batch_alter_table('project_analyses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_analysis_project_user', type_='unique')
        batch_op.drop_index('ix_analyses_user_computed')

    with op.batch_alter_table('exchange_connections', schema=None) as batch_op:
        batch_op.drop_index('uq_connections_user_exchange', sqlite_where=sa.text("platform != 'tg_channel'"), postgresql_where=sa.text("platform != 'tg_channel'"))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clients_user_platform_client', type_='unique')

    # ### end Alembic commands ###
