"""v2 initial schema

Revision ID: 66c6c53196b8
Revises: 
Create Date: 2026-07-25 12:12:59.200642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66c6c53196b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('target_hourly_rate', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('trial', 'basic', 'pro', 'business', name='subscriptiontier', native_enum=False, length=32), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('auto_send_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_send_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_client_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('new_lead', 'proposal_sent', 'negotiation', 'won', 'lost', 'in_progress', 'completed', 'repeat_client', name='pipelinestage', native_enum=False, length=32), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_platform_client_id'), 'clients', ['platform_client_id'], unique=False)
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_table('exchange_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('kwork', 'fl_ru', 'weblancer', 'tg_channel', 'upwork', name='platform', native_enum=False, length=32), nullable=False),
    sa.Column('credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'error', name='connectionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_connections_user_id'), 'exchange_connections', ['user_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_user_id'), 'portfolio_items', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('trial', 'basic', 'pro', 'business', name='subscriptiontier', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('message', 'note', 'reminder', name='interactiontype', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_client_id'), 'interactions', ['client_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_connection_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('kwork', 'fl_ru', 'weblancer', 'tg_channel', 'upwork', name='platform', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('budget_raw', sa.String(length=255), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('proposals_count', sa.Integer(), nullable=True),
    sa.Column('client_rating', sa.Float(), nullable=True),
    sa.Column('client_orders', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_connection_id'], ['exchange_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_projects_source_ext')
    )
    op.create_index(op.f('ix_projects_external_id'), 'projects', ['external_id'], unique=False)
    op.create_index(op.f('ix_projects_source'), 'projects', ['source'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'notified', 'done', 'cancelled', name='reminderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_client_id'), 'reminders', ['client_id'], unique=False)
    op.create_index(op.f('ix_reminders_due_at'), 'reminders', ['due_at'], unique=False)
    op.create_table('project_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extracted_budget', sa.Integer(), nullable=True),
    sa.Column('extracted_deadline_days', sa.Integer(), nullable=True),
    sa.Column('extracted_skills', sa.JSON(), nullable=False),
    sa.Column('client_red_flags', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('profitability_index', sa.Float(), nullable=True),
    sa.Column('effective_hourly_rate', sa.Float(), nullable=True),
    sa.Column('net_payout', sa.Float(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('needs_manual_review', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_analyses_project_id'), 'project_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_analyses_user_id'), 'project_analyses', ['user_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'edited', 'sent', name='proposalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('mode', sa.Enum('template', 'ai', name='proposalmode', native_enum=False, length=32), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_project_id'), 'proposals', ['project_id'], unique=False)
    op.create_index(op.f('ix_proposals_user_id'), 'proposals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_user_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_project_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_project_analyses_user_id'), table_name='project_analyses')
    op.drop_index(op.f('ix_project_analyses_project_id'), table_name='project_analyses')
    op.drop_table('project_analyses')
    op.drop_index(op.f('ix_reminders_due_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_client_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_projects_source'), table_name='projects')
    op.drop_index(op.f('ix_projects_external_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_interactions_client_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_portfolio_items_user_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_exchange_connections_user_id'), table_name='exchange_connections')
    op.drop_table('exchange_connections')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_platform_client_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
